// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQh68RMTc_GAjzA9RnR6M51T3OcUTLDfY',
    appId: '1:451535971643:web:70b0fc0aeb6dedc3f0c31e',
    messagingSenderId: '451535971643',
    projectId: 'petbondhubd',
    authDomain: 'petbondhubd.firebaseapp.com',
    storageBucket: 'petbondhubd.firebasestorage.app',
    measurementId: 'G-4N5NFYZRL1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5wT5f8WTwVb3MVl8eliC8U0DWDzKZqYI',
    appId: '1:451535971643:android:58c3d59f5c0b7af7f0c31e',
    messagingSenderId: '451535971643',
    projectId: 'petbondhubd',
    storageBucket: 'petbondhubd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALajUMkZZ1wBtuput6j3_qYgFk0LhmawM',
    appId: '1:451535971643:ios:5f76b887f83b59f9f0c31e',
    messagingSenderId: '451535971643',
    projectId: 'petbondhubd',
    storageBucket: 'petbondhubd.firebasestorage.app',
    iosBundleId: 'com.example.petbondhu',
  );

}