// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzBekP-wmfZLbG7KWc3_Dkb3LUvF6O6s4',
    appId: '1:992733149716:web:c555a406fe7f68de650501',
    messagingSenderId: '992733149716',
    projectId: 'petbondhu1',
    authDomain: 'petbondhu1.firebaseapp.com',
    storageBucket: 'petbondhu1.firebasestorage.app',
    measurementId: 'G-SH2QNS3SSW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGTjwXwCA1RywcIXKsIv1QfM5KTSeW574',
    appId: '1:992733149716:android:4cc410b67c2d180f650501',
    messagingSenderId: '992733149716',
    projectId: 'petbondhu1',
    storageBucket: 'petbondhu1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLyVAzSW9NUvEYyOHzHHNz-lG7apnVkB0',
    appId: '1:992733149716:ios:4ef0f97cd623235c650501',
    messagingSenderId: '992733149716',
    projectId: 'petbondhu1',
    storageBucket: 'petbondhu1.firebasestorage.app',
    iosClientId: '992733149716-3c883u62pco8ik9eaahu1feoj4hk22ja.apps.googleusercontent.com',
    iosBundleId: 'com.example.petbondhu1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLyVAzSW9NUvEYyOHzHHNz-lG7apnVkB0',
    appId: '1:992733149716:ios:4ef0f97cd623235c650501',
    messagingSenderId: '992733149716',
    projectId: 'petbondhu1',
    storageBucket: 'petbondhu1.firebasestorage.app',
    iosClientId: '992733149716-3c883u62pco8ik9eaahu1feoj4hk22ja.apps.googleusercontent.com',
    iosBundleId: 'com.example.petbondhu1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzBekP-wmfZLbG7KWc3_Dkb3LUvF6O6s4',
    appId: '1:992733149716:web:5271cbb70b3386e9650501',
    messagingSenderId: '992733149716',
    projectId: 'petbondhu1',
    authDomain: 'petbondhu1.firebaseapp.com',
    storageBucket: 'petbondhu1.firebasestorage.app',
    measurementId: 'G-Y1SDKQ5Z00',
  );

}