// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlMN9lstLlEDtIpl1QV0fr2yupm3wrPYY',
    appId: '1:397829468409:web:60319637ce6cd615643228',
    messagingSenderId: '397829468409',
    projectId: 'petapp-225ec',
    authDomain: 'petapp-225ec.firebaseapp.com',
    storageBucket: 'petapp-225ec.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoTs8KB_CewL1W6Q-CLkDxKQ3_NdhQqsw',
    appId: '1:397829468409:android:f1c3eeac66d785a8643228',
    messagingSenderId: '397829468409',
    projectId: 'petapp-225ec',
    storageBucket: 'petapp-225ec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwlOhoMkpB-rvHMyMhTrqcYBac4sRoSx0',
    appId: '1:397829468409:ios:9675e7dcf4648986643228',
    messagingSenderId: '397829468409',
    projectId: 'petapp-225ec',
    storageBucket: 'petapp-225ec.firebasestorage.app',
    iosClientId: '397829468409-jgjncdojcjue9vfj3ler2eksuo3pclcn.apps.googleusercontent.com',
    iosBundleId: 'com.example.petapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlMN9lstLlEDtIpl1QV0fr2yupm3wrPYY',
    appId: '1:397829468409:web:9158f512e84a332e643228',
    messagingSenderId: '397829468409',
    projectId: 'petapp-225ec',
    authDomain: 'petapp-225ec.firebaseapp.com',
    storageBucket: 'petapp-225ec.firebasestorage.app',
  );
}
